import 'dotenv/config';
import { getSupabaseAdmin } from './supabase';

const PRODUCTS = [
  {
    title: 'Signature Cashmere Overcoat',
    description: 'Precision-tailored in Milan from recycled fibers. A timeless piece for the modern wardrobe.',
    price_current: 895.00,
    currency_code: 'USD',
    merchant_platform: 'amazon',
    merchant_name: 'Amazon',
    thumbnail_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    category: 'Apparel',
    brand: 'Lumina',
    asin: 'B0CQMJ8K2L',
    match_method: 'exact_code',
    match_confidence: 0.980,
  },
  {
    title: 'Velocity Pro Runner',
    description: 'Sleek aerodynamic performance sneaker with responsive cushioning and breathable knit upper.',
    price_current: 240.00,
    price_original: 300.00,
    currency_code: 'USD',
    merchant_platform: 'flipkart',
    merchant_name: 'Flipkart',
    thumbnail_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    category: 'Footwear',
    brand: 'Velocity',
    sku: 'VEL-RN-001',
    match_method: 'exact_code',
    match_confidence: 0.995,
  },
  {
    title: 'Lumina Structured Tote',
    description: 'Premium full-grain leather tote with hand-stitched detailing and gold-toned hardware.',
    price_current: 450.00,
    currency_code: 'USD',
    merchant_platform: 'ebay',
    merchant_name: 'eBay',
    thumbnail_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
    category: 'Accessories',
    brand: 'Lumina',
    upc: '840394102394',
    match_method: 'exact_code',
    match_confidence: 0.970,
  },
  {
    title: 'S1 Chronos Smartwatch',
    description: 'Advanced health monitoring with AMOLED display, 14-day battery life, and premium titanium build.',
    price_current: 399.00,
    price_original: 499.00,
    currency_code: 'USD',
    merchant_platform: 'croma',
    merchant_name: 'Croma',
    thumbnail_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    category: 'Electronics',
    brand: 'Chronos',
    model_number: 'S1-2024-BLK',
    match_method: 'exact_code',
    match_confidence: 0.990,
  },
  {
    title: 'Organic Heavy Tee (2-Pack)',
    description: 'Ultra-soft 320GSM organic cotton heavyweight tees. Pre-shrunk and garment-dyed for a lived-in feel.',
    price_current: 85.00,
    currency_code: 'USD',
    merchant_platform: 'meesho',
    merchant_name: 'Meesho',
    thumbnail_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    category: 'Apparel',
    brand: 'Essentials',
    sku: 'ORG-HT-2PK',
    match_method: 'fuzzy_tokens',
    match_confidence: 0.850,
  },
  {
    title: 'Hand-Burnished Moto Jacket',
    description: 'Individually treated by artisans in Tuscany for a unique patina that evolves over time.',
    price_current: 1250.00,
    currency_code: 'USD',
    merchant_platform: 'amazon',
    merchant_name: 'Amazon',
    thumbnail_url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    category: 'Apparel',
    brand: 'Artisan Leather Co.',
    asin: 'B0D3K7L9M1',
    match_method: 'exact_code',
    match_confidence: 0.975,
  },
  {
    title: 'Wireless Noise-Canceling Headphones',
    description: 'Industry-leading ANC with adaptive transparency mode. 40-hour battery life with quick charge.',
    price_current: 349.00,
    price_original: 399.00,
    currency_code: 'USD',
    merchant_platform: 'flipkart',
    merchant_name: 'Flipkart',
    thumbnail_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    category: 'Electronics',
    brand: 'Sonic',
    model_number: 'SN-1000-ANC',
    match_method: 'exact_code',
    match_confidence: 0.985,
  },
  {
    title: 'Minimalist Desk Lamp',
    description: 'Adjustable LED desk lamp with wireless charging base, warm-to-cool temperature control, and memory settings.',
    price_current: 189.00,
    currency_code: 'USD',
    merchant_platform: 'amazon',
    merchant_name: 'Amazon',
    thumbnail_url: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800',
    category: 'Home',
    brand: 'Nordic House',
    asin: 'B0D5X2Y3Z4',
    match_method: 'fuzzy_tokens',
    match_confidence: 0.820,
  },
  {
    title: 'Ceramic Pour-Over Coffee Set',
    description: 'Hand-thrown ceramic dripper with double-wall glass carafe. Made by artisans in Kyoto.',
    price_current: 120.00,
    currency_code: 'USD',
    merchant_platform: 'ebay',
    merchant_name: 'eBay',
    thumbnail_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    category: 'Home',
    brand: 'Kyoto Craft',
    ean: '4901234567890',
    match_method: 'exact_code',
    match_confidence: 0.960,
  },
  {
    title: 'Performance Yoga Mat',
    description: '6mm natural tree rubber mat with microfiber suede top layer. Non-slip wet or dry.',
    price_current: 98.00,
    price_original: 128.00,
    currency_code: 'USD',
    merchant_platform: 'meesho',
    merchant_name: 'Meesho',
    thumbnail_url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800',
    category: 'Fitness',
    brand: 'Asana',
    sku: 'ASA-YM-6MM',
    match_method: 'fuzzy_tokens',
    match_confidence: 0.780,
  },
  {
    title: 'Slim Leather Cardholder',
    description: 'RFID-blocking Italian leather cardholder. Holds up to 8 cards with a quick-access pull tab.',
    price_current: 65.00,
    currency_code: 'USD',
    merchant_platform: 'croma',
    merchant_name: 'Croma',
    thumbnail_url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
    category: 'Accessories',
    brand: 'Lumina',
    model_number: 'LCH-001-BLK',
    match_method: 'exact_code',
    match_confidence: 0.990,
  },
  {
    title: 'Smart Home Hub Display',
    description: '10-inch smart display with Matter compatibility, built-in Zigbee radio, and gesture controls.',
    price_current: 229.00,
    price_original: 279.00,
    currency_code: 'USD',
    merchant_platform: 'flipkart',
    merchant_name: 'Flipkart',
    thumbnail_url: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800',
    category: 'Electronics',
    brand: 'HomeCore',
    model_number: 'HC-DISP-10',
    match_method: 'exact_code',
    match_confidence: 0.965,
  },
  {
    title: 'Merino Wool Throw Blanket',
    description: 'Ultra-soft 100% Merino wool throw. Ethically sourced and manufactured in a carbon-neutral facility.',
    price_current: 175.00,
    currency_code: 'USD',
    merchant_platform: 'amazon',
    merchant_name: 'Amazon',
    thumbnail_url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    category: 'Home',
    brand: 'Woolmark',
    asin: 'B0D7A8B9C0',
    match_method: 'fuzzy_tokens',
    match_confidence: 0.840,
  },
  {
    title: 'Bamboo Wireless Keyboard',
    description: 'Full-size mechanical keyboard with bamboo wood case, hot-swappable switches, and USB-C.',
    price_current: 159.00,
    currency_code: 'USD',
    merchant_platform: 'ebay',
    merchant_name: 'eBay',
    thumbnail_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800',
    category: 'Electronics',
    brand: 'TypeCraft',
    upc: '749301274930',
    match_method: 'exact_code',
    match_confidence: 0.955,
  },
  {
    title: 'Cold Brew Concentrate Gift Set',
    description: 'Set of 3 small-batch organic cold brew blends. Includes reusable glass carafe and recipe cards.',
    price_current: 54.00,
    currency_code: 'USD',
    merchant_platform: 'meesho',
    merchant_name: 'Meesho',
    thumbnail_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=800',
    category: 'Food & Drink',
    brand: 'Brew Co.',
    sku: 'BC-CB-GIFT-3',
    match_method: 'fuzzy_tokens',
    match_confidence: 0.720,
  },
];

async function seed() {
  console.log('Connecting to Supabase...');
  const admin = getSupabaseAdmin();

  console.log(`Inserting ${PRODUCTS.length} products...`);

  const { error } = await admin.from('products').insert(PRODUCTS);

  if (error) {
    console.error('Insert error:', error.message);
    process.exit(1);
  }

  console.log(`Successfully inserted ${PRODUCTS.length} products.`);
  console.log('Products added:');
  PRODUCTS.forEach(p => console.log(`  \u2022 ${p.title} (${p.currency_code} ${p.price_current})`));
}

seed().catch(err => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
